// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsC44f9Pb-rV62Gn0q3TUbJycy9vZjk2E',
    appId: '1:1097363809536:web:0aae8f6c121860c4fc7fe5',
    messagingSenderId: '1097363809536',
    projectId: 'plant-e88f8',
    authDomain: 'plant-e88f8.firebaseapp.com',
    storageBucket: 'plant-e88f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlN_iqUflJ9beZAbJQZ4po06-UAcDKfzk',
    appId: '1:1097363809536:android:eb38ac1059238293fc7fe5',
    messagingSenderId: '1097363809536',
    projectId: 'plant-e88f8',
    storageBucket: 'plant-e88f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlduMzGmdITCqdeTPv5oVlBxu7EP3oCC0',
    appId: '1:1097363809536:ios:cd4797aad5093f49fc7fe5',
    messagingSenderId: '1097363809536',
    projectId: 'plant-e88f8',
    storageBucket: 'plant-e88f8.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlduMzGmdITCqdeTPv5oVlBxu7EP3oCC0',
    appId: '1:1097363809536:ios:cd4797aad5093f49fc7fe5',
    messagingSenderId: '1097363809536',
    projectId: 'plant-e88f8',
    storageBucket: 'plant-e88f8.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsC44f9Pb-rV62Gn0q3TUbJycy9vZjk2E',
    appId: '1:1097363809536:web:4532f32fddd81f24fc7fe5',
    messagingSenderId: '1097363809536',
    projectId: 'plant-e88f8',
    authDomain: 'plant-e88f8.firebaseapp.com',
    storageBucket: 'plant-e88f8.appspot.com',
  );
}
